# Generated by Django 3.0.2 on 2020-01-29 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200130_0247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name': 'Admin', 'verbose_name_plural': 'Admins'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('lab', 'schedule', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('lab', 'time')},
        ),
    ]
