# Generated by Django 3.0.2 on 2020-01-31 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200131_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='time_created',
            new_name='created_at',
        ),
    ]
