# Generated by Django 3.0.2 on 2020-02-01 11:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('api', '0009_timetable'), ('api', '0010_auto_20200201_1059')]

    dependencies = [
        ('api', '0008_auto_20200131_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('week', models.CharField(choices=[('odd', 'Odd'), ('even', 'Even'), ('all', 'All')], default='all', max_length=4)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Lab')),
                ('end_at', models.TimeField()),
                ('start_at', models.TimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
