# Generated by Django 3.0.2 on 2020-02-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_timetable_squashed_0010_auto_20200201_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('first_week', models.DateField()),
                ('year_start', models.IntegerField()),
            ],
        ),
    ]
