# Generated by Django 3.0.2 on 2020-02-01 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_add_relationships_from_timetable_to_semester'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('number', 'year_start')},
        ),
    ]
