# Generated by Django 3.0.2 on 2020-02-01 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_add_unique_constraints_for_semester_model'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('lab_id', 'semester_id')},
        ),
    ]
