# Generated by Django 3.0.2 on 2020-02-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_add_default_value_for_attendance_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='end_week',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='timetable',
            name='start_week',
            field=models.IntegerField(),
        ),
    ]
