# Generated by Django 3.0.2 on 2020-02-03 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_add_start_week_and_end_week_for_timetable'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lab',
            unique_together={('name', 'course')},
        ),
    ]
